### ISSUE TITLE
General direction

### ISSUE THREAD

**Issue by fmaussion** [OGGM/glacier_simulator#1]
I really like the app, this is going in the perfect direction!

A few quick thoughts (not much time today):
- the "climate" part should be left for another app. I.e this app focuses on glacier shape and size
- as such, the "simulation time" slider should be removed and all runs should be "run_until_equilibrium"
- is there a way to signify in the app that the glacier is running? I.e. show the current simulation year or volume change or something....
- if there is a way to include the slope of the bed as slider that would be awesome ( maybe this could replace the choice for parabola or trapeze, which is too complex at this stage
- the lower plot (glacier shape) could also be filled with a glacier 
- another bedrock profile: wide at the top, narrow at the bottom

**Comment by pat-schmitt** [comment]
more thoughts:

- advanced section (change mass balance gradient, ice flow parameters, ...)
- design (colors, annotation, ...)
- Text field for showing progress
- hover for some explanations (ELA, annual mass balance, ...)
- old glacier is hidden by new one when new one is advancing (change alpha of new one)
- maybe add climate for idealized glaciers

**Comment by fmaussion** [comment]
I've just added a `model.get_diagnostics()` method to OGGM: https://github.com/OGGM/oggm/pull/853

I recommend to try it out -> with this you have access to new variables like velocity along the profile -> more and more ideas ;-)
