### ISSUE TITLE
Wrong area calculation for mass balance plot and glacier wide mass balance

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/glacier_simulator#13]
While programming the AAR I looked over the area calculation for the glacier wide mass balance and saw that I calculated the area and the whole glacier wide mass balance with a wrong model picture in mind. I orientated myself more in how the plot is showing the area than the model intern area is handled.

To make clear what I mean here a small draft when looking from above, the indices show grid points, first row current implementation in the simulator, second row how the model area looks like

![20201203_105432](https://user-images.githubusercontent.com/50843444/100994263-b3817f00-3556-11eb-8f43-89ff2d57b65b.jpg)

So currently the area is calculated using a trapezoidal area between grid points and the mass balance is calculated at the mean elevation of this trapezoid. And the area around the ELA is accounted partly to the accumulation and partly to the ablation area, depending on where the ELA is located relative in the cell.

So my plan is to use now the model point of view and using the model bin_area, and just use the surface_h to determine if the area shoulf count for the accumulation or ablation area (so no area splitting in one cell according to ELA position)

@fmaussion what do you think?

**Comment by fmaussion** [comment]
Haha, quite fun ;-).

I agree that using trapeze is not good because internally, the model does not do that.

Now you are suggesting a fractional bin area, which is OK, but... to be honest I would  do it even much simpler. Maybe I'm seeing this wrong, but in OGGM the AAR is calculated as:

```python
h, w, mbh = mbmod.get_annual_mb_on_flowlines()
pacc = np.where(mbh >= 0)
aar = np.sum(w[pacc]) / np.sum(w)
```

Does this help or not?

**Comment by pat-schmitt** [comment]
For the AAR I used:
```
total_area = model.fls[0].area_m2
accumulation_area = np.sum(np.where(model.fls[0].surface_h > mb_model.ela_h,
                                    model.fls[0].bin_area_m2,
                                    0))
AAR = accumulation_area / total_area
```

which is more or less the same as you posted I think. So for the AAR calculation I do not use a fractional bin area.

But I use fractional bin area for the mb plot, because if not it looks like this (I just remembered that was why I introduced it):
![mb_discrete](https://user-images.githubusercontent.com/50843444/101003624-9f427f80-3560-11eb-80c8-e56a4e804592.png)

So by using the fractional bin area I hide the discrete model behind a smoothed curve ;)

**Comment by fmaussion** [comment]
I understand! Thanks

**Comment by pat-schmitt** [comment]
Equations for trapezoidal subarea calculations, just for documentation:
![20201220_192906](https://user-images.githubusercontent.com/50843444/102721260-03539a80-42fa-11eb-9aa5-a97ece0a52b0.jpg)
![20201220_192640](https://user-images.githubusercontent.com/50843444/102721270-0cdd0280-42fa-11eb-9fce-cdd1f54bb0e2.jpg)
