### ISSUE TITLE
AttributeError in _compute_group_range for linked plots in Holoviews version 1.14.0

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/glacier_simulator#14]
With Holoviews 1.14.0 an AttributeError occurs. 
This problem is already solved (see https://github.com/holoviz/holoviews/pull/4742). 
Until Holoviews 1.14.1 is released I pin the Holoviews version to 1.13.5.

**Comment by fmaussion** [comment]
https://github.com/holoviz/holoviews/releases/tag/v1.14.1

**Comment by pat-schmitt** [comment]
Yes today in the morning the new version 1.14.1 was not in the conda-forge but now it is, so I test it right now...

**Comment by pat-schmitt** [comment]
Ok the new version is only on the conda-forge homepage now, but when tipping `conda update holoviews ` only version 1.14.0 is found. Maybe it take some time until the new version is really available, but I will try again tomorrow

**Comment by fmaussion** [comment]
ok no stress. Maybe we can ask @TimoRoth for when this version will hit our Docker images as well, since we need that to update the simulator on the bokeh server?

**Comment by TimoRoth** [comment]
Unless it came out today, it should already be part of the latest untested_base image, since those are auto-built every Sunday.

**Comment by pat-schmitt** [comment]
Ok, yes it came out today an hour ago, so we must wait until next Sunday

**Comment by TimoRoth** [comment]
I can also just re-run yesterdays build: https://github.com/OGGM/OGGM-Docker/actions/runs/446460336
Should show up here in a few hours: https://hub.docker.com/r/oggm/untested_base/tags

**Comment by pat-schmitt** [comment]
Ok I tested Holoviews 1.14.1 on my computer and it is working, so I will unpin the Holoviews version again.

I have a question regarding the docker image. I want to check which version of Holoviews is installed in the new image oggm/bokeh:20201228. 
To list all packages from oggm/untested_base:20201228 I use: `docker run -it oggm/untested_base:20201228 bash`
and then `pip list`.
But this do not work with oggm/bokeh:20201228, I think because this image execute a data ( `ENTRYPOINT ["/home/bokeh/run.sh"]`) when it is started. But I am not sure. So is there a other way to check the python versions?

**Comment by fmaussion** [comment]
@TimoRoth what is the HoloViews version on `oggm/bokeh:20201228` ?
