### ISSUE TITLE
Possible change in text interface

### ISSUE THREAD

**Issue by fmaussion** [OGGM/glacier_simulator#15]
In the current advanced interface the text looks like:

Years to advance model: **150**

Would if be to have a changing text so that it reads:

Advance the model for **X** years

Where "X" is updated with the slider?

**Comment by pat-schmitt** [comment]
Yes this is possible I think, I will give it a try

**Comment by pat-schmitt** [comment]
I also changed the interface for the "Show model progress" selector and  "Abort model after" slider in "Model opt.".
