### ISSUE TITLE
Add current app version to interface somewhere

### ISSUE THREAD

**Issue by fmaussion** [OGGM/glacier_simulator#16]
I'll give you tools to do that, but it would be nice to have the app version displayed. I'll do it for the explorer first then we can add it here.

**Comment by fmaussion** [comment]
Ok so with https://github.com/OGGM/glacier_simulator/commit/e64c3d7fbad1e6ed9da4d3949b65b9b609c951cf I added a version.py to the repo.

From the notebook you should be able to do `from .version import __version__`. 

Can you add this text as a small addition somewhere? I thought either:
- right next to the title: very (maybe too?) prominent
- at the same height of the title but right aligned
- below the option config box and just above the logos ("Glacier simulator v1.X")
- next to the language tickboxes

Or anything you might find better! Thoughts?

**Comment by pat-schmitt** [comment]
Here are some options all together:

![possible_version_number_positions](https://user-images.githubusercontent.com/50843444/103350982-042ac000-4aa2-11eb-9de2-d54e63c2e1e9.png)

I think it is enough to keep the version number in the tab heading and above the language selection (with a other version at the side of the language selection):

![other_version](https://user-images.githubusercontent.com/50843444/103353588-88347600-4aa9-11eb-9663-84ad960fcbd2.png)
