### ISSUE TITLE
Allow ELA values above the maximum glacier bed height

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/glacier_simulator#21]
This will need some rearrangement of the internal calculations of the percentages of the bin area (colours in the top right plot).

**Comment by fmaussion** [comment]
Yes, and also some kind of warning in the lower right text box when there is no ice yet  and the ELA is above the top.

**Comment by pat-schmitt** [comment]
Finally implemented with https://github.com/OGGM/glacier_simulator/commit/eb42ffc49e975e9625e0508161856b7a92d92558 (thanks to a push from @lilianschuster).
