### ISSUE TITLE
Is it possible to have persistence in beginner mode?

### ISSUE THREAD

**Issue by fmaussion** [OGGM/glacier_simulator#23]
For some experiments it would be very nice to have two buttons in beginner mode:

- reset and run
- advance 

would it be possible?

**Comment by pat-schmitt** [comment]
yes of course this is possible. You mean:

- reset and run: same as current beginner mode button
- advance: same as current advanced mode 'Run to equilibrium' button

If so this would be very easy.

**Comment by fmaussion** [comment]
Yes exactly - I believe this is not too complicated and actually allows a lot of ELA experiments without leaving the beginner mode, in particular thanks to the timeseries graph

**Comment by pat-schmitt** [comment]
Just added in https://github.com/OGGM/glacier_simulator/commit/82d5b2f8d8374eeb91cfec06b12c037e9219e367

**Comment by fmaussion** [comment]
Awesome! I think it would be even simpler and more intuitive with the two buttons:

- reset
- run to equilibrium

what do you think?

**Comment by pat-schmitt** [comment]
Or even more explicit:

- Reset and run to equilibrium
- Run to equilibrium

?

**Comment by fmaussion** [comment]
Only if its easier for you - simply reset and do nothing is valid and most intuitive I think.

**Comment by pat-schmitt** [comment]
Ah, now I understand. Yes this is possible and probably most intutitive

**Comment by pat-schmitt** [comment]
Ok now changed to "Reset" and "Run to equilibrium" (in https://github.com/OGGM/glacier_simulator/commit/db3bf81b6b0e3de8f6b6af573835850e813dc200).
