### ISSUE TITLE
Timeseries could be stored even when "Show timeseries" is off

### ISSUE THREAD

**Issue by fmaussion** [OGGM/glacier_simulator#7]
Timeseries could be stored in an arry even when "Show timeseries" is off. This way, the plots could be displayed after a run - and one could still have a faster run as well.

**Comment by pat-schmitt** [comment]
Yes good point.

So i changed now the whole updating thing. Now the timeseries plot always updates at the end of the model run and the geometry plot update during the model run is optional. But at the end of the model run both plots always show the current state. It is now also possible to switch off both updates to save computation time (need than only approximately 1/3 of time with updates) and only look at the end of the run how the glacier looks.

**Comment by fmaussion** [comment]
I'm not sure to understand but thanks! I'll give it a try later today
