### ISSUE TITLE
If model opt is to show model progress every X years, the timeseries plot should also adapt the timestep

### ISSUE THREAD

**Issue by fmaussion** [OGGM/glacier_simulator#8]
cc @pat-schmitt

**Comment by pat-schmitt** [comment]
This is already the case. However you can only see the timesteps of the the timeseries plot when using the hover. So maybe I could include points in the timeseries plot to actually see where there are values and where are only connecting lines between this values.

A other thing is that when you change the progress every X year you must click on the button below so the new option is set. Maybe I will get rid of this button and always use the values of the sliders at the start of a new run.

**Comment by fmaussion** [comment]
I forgot the button! Thanks for pointing it out.

What are the downsides to removing this button?

**Comment by pat-schmitt** [comment]
I found it more intuitive that you see the current settings before you start a run in the small info text. 
But now I think it is also fine that the info text shows the settings of the last run and always use the values of the sliders at the start of a new run. In this case the button is not needed anymore.

**Comment by fmaussion** [comment]
>  So maybe I could include points in the timeseries plot to actually see where there are

No, this is not necessary (I forgot to click the button)
